package chunk

import (
	"context"

	"github.com/i33ym/dory"
)

// ContextualConfig configures the contextual retrieval chunking strategy.
type ContextualConfig struct {
	// Size is the maximum number of characters per chunk.
	Size int

	// Overlap is the number of characters shared between consecutive chunks.
	Overlap int

	// ContextFunc generates a short context prefix for a chunk given the
	// full document content and the chunk text. Typically backed by an LLM.
	ContextFunc func(ctx context.Context, docContent string, chunkText string) (string, error)
}

// Contextual splits documents into fixed-size chunks and prepends each with
// a short context sentence generated by ContextFunc. This gives the embedder
// more context about where the chunk fits in the document.
type Contextual struct {
	config ContextualConfig
}

// NewContextual creates a new contextual retrieval splitter.
func NewContextual(config ContextualConfig) *Contextual {
	return &Contextual{config: config}
}

// Split implements the [dory.Splitter] interface.
func (c *Contextual) Split(ctx context.Context, doc *dory.Document) ([]*dory.Chunk, error) {
	content, err := doc.Content().Text()
	if err != nil {
		return nil, err
	}

	size := c.config.Size
	overlap := c.config.Overlap

	if size <= 0 {
		size = 512
	}
	if overlap < 0 || overlap >= size {
		overlap = 0
	}

	if len(content) == 0 {
		return nil, nil
	}

	// Split into fixed-size chunks.
	var chunks []*dory.Chunk
	step := size - overlap
	for i := 0; i < len(content); i += step {
		end := min(i+size, len(content))
		text := content[i:end]

		// Generate context prefix.
		prefix, err := c.config.ContextFunc(ctx, content, text)
		if err != nil {
			return nil, err
		}

		chunk := dory.NewChunkWithOptions(
			doc.ID()+"-"+itoa(len(chunks)),
			doc.ID(),
			text,
			copyMeta(doc.Metadata()),
			doc.SourceURI(),
			&dory.Position{StartByte: i, EndByte: end},
			0,
		)
		chunk.ContextPrefix = prefix
		chunks = append(chunks, chunk)

		if end == len(content) {
			break
		}
	}
	return chunks, nil
}
